# Generated by Django 5.1 on 2026-03-04 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.BigIntegerField(help_text='ID único de la carta en la API de YGOProDeck', primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('ygoprodeck_url', models.URLField(blank=True, default='', max_length=500)),
                ('type', models.CharField(help_text='Tipo completo: "Normal Monster", "Spell Card", "Link Monster", etc.', max_length=100)),
                ('human_readable_card_type', models.CharField(blank=True, default='', help_text='Tipo legible: "Normal Monster", "Normal Spell", "Link Effect Monster"', max_length=100)),
                ('frame_type', models.CharField(blank=True, default='', help_text='Tipo de marco: normal, effect, spell, trap, link, xyz, synchro, fusion, effect_pendulum, etc.', max_length=50)),
                ('race', models.CharField(blank=True, default='', help_text='Tipo de monstruo (Spellcaster, Dragon) o subtipo de spell/trap (Normal, Continuous)', max_length=100)),
                ('archetype', models.CharField(blank=True, default='', help_text='Arquetipo al que pertenece la carta', max_length=255)),
                ('typeline', models.JSONField(blank=True, help_text='Array de strings con la línea de tipo: ["Dragon", "Pendulum", "Effect"]', null=True)),
                ('desc', models.TextField(blank=True, default='', help_text='Descripción/efecto completo de la carta')),
                ('pend_desc', models.TextField(blank=True, default='', help_text='Descripción del efecto péndulo (solo cartas Pendulum)')),
                ('monster_desc', models.TextField(blank=True, default='', help_text='Descripción del efecto de monstruo (solo cartas Pendulum)')),
                ('atk', models.IntegerField(blank=True, help_text='Puntos de ataque (null para Spell/Trap)', null=True)),
                ('defense', models.IntegerField(blank=True, help_text='Puntos de defensa (null para Link y Spell/Trap)', null=True)),
                ('level', models.IntegerField(blank=True, help_text='Nivel/Rango del monstruo (0 para Link, null para Spell/Trap)', null=True)),
                ('attribute', models.CharField(blank=True, default='', help_text='Atributo: DARK, LIGHT, WATER, FIRE, EARTH, WIND, DIVINE', max_length=20)),
                ('linkval', models.IntegerField(blank=True, help_text='Valor de Link (solo monstruos Link)', null=True)),
                ('linkmarkers', models.JSONField(blank=True, help_text='Marcadores Link: ["Top", "Bottom-Left", "Bottom-Right"]', null=True)),
                ('scale', models.IntegerField(blank=True, help_text='Escala Péndulo (solo cartas Pendulum)', null=True)),
            ],
            options={
                'verbose_name': 'Carta',
                'verbose_name_plural': 'Cartas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BanlistInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ban_tcg', models.CharField(blank=True, choices=[('Forbidden', 'Forbidden'), ('Limited', 'Limited'), ('Semi-Limited', 'Semi-Limited')], default='', help_text='Estado en la banlist TCG', max_length=20)),
                ('ban_ocg', models.CharField(blank=True, choices=[('Forbidden', 'Forbidden'), ('Limited', 'Limited'), ('Semi-Limited', 'Semi-Limited')], default='', help_text='Estado en la banlist OCG', max_length=20)),
                ('ban_goat', models.CharField(blank=True, choices=[('Forbidden', 'Forbidden'), ('Limited', 'Limited'), ('Semi-Limited', 'Semi-Limited')], default='', help_text='Estado en la banlist GOAT format', max_length=20)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banlist_info', to='api_yugioh.card')),
            ],
            options={
                'verbose_name': 'Info de Banlist',
                'verbose_name_plural': 'Info de Banlists',
            },
        ),
        migrations.CreateModel(
            name='CardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.BigIntegerField(help_text='ID de la imagen en la API')),
                ('image_url', models.URLField(help_text='URL de la imagen completa', max_length=500)),
                ('image_url_small', models.URLField(blank=True, default='', help_text='URL de la imagen en tamaño pequeño', max_length=500)),
                ('image_url_cropped', models.URLField(blank=True, default='', help_text='URL de la imagen recortada (solo el artwork)', max_length=500)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_images', to='api_yugioh.card')),
            ],
            options={
                'verbose_name': 'Imagen de Carta',
                'verbose_name_plural': 'Imágenes de Cartas',
            },
        ),
        migrations.CreateModel(
            name='CardPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardmarket_price', models.DecimalField(blank=True, decimal_places=2, help_text='Precio en Cardmarket (EUR)', max_digits=10, null=True)),
                ('tcgplayer_price', models.DecimalField(blank=True, decimal_places=2, help_text='Precio en TCGPlayer (USD)', max_digits=10, null=True)),
                ('ebay_price', models.DecimalField(blank=True, decimal_places=2, help_text='Precio en eBay (USD)', max_digits=10, null=True)),
                ('amazon_price', models.DecimalField(blank=True, decimal_places=2, help_text='Precio en Amazon (USD)', max_digits=10, null=True)),
                ('coolstuffinc_price', models.DecimalField(blank=True, decimal_places=2, help_text='Precio en CoolStuffInc (USD)', max_digits=10, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_prices', to='api_yugioh.card')),
            ],
            options={
                'verbose_name': 'Precio de Carta',
                'verbose_name_plural': 'Precios de Cartas',
            },
        ),
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_name', models.CharField(help_text='Nombre del set', max_length=255)),
                ('set_code', models.CharField(help_text='Código del set: LOB-005', max_length=50)),
                ('set_rarity', models.CharField(help_text='Rareza: Ultra Rare, Common, etc.', max_length=100)),
                ('set_rarity_code', models.CharField(blank=True, default='', help_text='Código de rareza: (UR), (C), (ScR)', max_length=20)),
                ('set_price', models.DecimalField(blank=True, decimal_places=2, help_text='Precio del set', max_digits=10, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_sets', to='api_yugioh.card')),
            ],
            options={
                'verbose_name': 'Set de Carta',
                'verbose_name_plural': 'Sets de Cartas',
                'ordering': ['set_name'],
            },
        ),
    ]
